language: objective-c
osx_image: xcode9.1
before_install:
- gem install cocoapods
- gem update fastlane --no-ri --no-rdoc --no-document
- pod repo update
script:
- .travis/build.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false