language: objective-c
osx_image: xcode10
before_install:
- gem install bundler
- bundle install
- bundle exec pod repo update
script:
- .travis/build.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false